outputs.tf

feat: added various exports

---

main.tf
variables.tf

feat: private cluster variables

---

main.tf
variables.tf

Code tested and deployed into production. Remember to add the feature flag before deploying: [Microsoft docs](https://learn.microsoft.com/azure/aks/azure-cni-powered-by-cilium?WT.mc_id=AZ-MVP-5004348#register-the-ciliumdataplanepreview-feature-flag)

feat: aks with cilium

---

variables.tf

feat: tag should be optional

---

outputs.tf

feat: Adds new output aks_id

---

variables.tf

docs: correct description of name variable

---

.github/workflows/scorecard.yml

ci: add scorecard workflow

---

main.tf
variables.tf

feat: add storage profile

---

main.tf
variables.tf

feat: add the option to specify sku_tier

---

outputs.tf

feat: add output for managed identity block

---

outputs.tf

feat: output oidc issuer url

---

main.tf
outputs.tf
variables.tf

feat: add support for enabling key vault secrets provider

---

main.tf

feat: add support for auto scaling of default node pool

---

main.tf

fix: add default tags to law

---

main.tf
variables.tf

feat: add support for spot nodes on additional node pool

---

main.tf
variables.tf

feat: add support for os config on additional node pool

---

main.tf
variables.tf

Adds support for configuring the parameter automatic_channel_upgrade.

feat: add support for automatic_channel_upgrade

---

main.tf

Adds support for changing os_sku on additional node pool.
Can be used to i.e. change to AzureLinux.

feat: add support for os_sku on additnl node pool

---

main.tf
variables.tf

feat: add run_command_enabled variable

---

main.tf
variables.tf

feat: add private_dns_zone_id

---

.github/workflows/automation.yml

Due to issues with signoff and v4 of the action.
Also corrects the permissions of the workflow.

build: rollback release-please version

---

README.md
main.tf
variables.tf

feat: add support for image_cleaner

---

README.md
main.tf
variables.tf

Need this feature to change vm_max_map_count to install opensearch on aks cluster.

feat: added sysctl_config

---

.github/workflows/automation.yml
.terraform-docs.yml
README.md
main.tf
variables.tf

feat: add upgrade_override parameter and update upgrade_settings
